# Generated by Django 4.1.4 on 2022-12-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_alter_comentario_autor_alter_comentario_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='coment',
            new_name='comentario',
        ),
    ]
